### PR TITLE
new Release with fixing Issue #70

### PR DESCRIPTION
**Pull request by rogrun**
Hello thetrueavatar,

please have a look on this PR. In the Changelog-en.md you'll find a overview of all changes. When you merge this PR, please compile a new .phar and update the docs. 

Let me know if any changes are needed.

Best Ronny

### CODE REVIEW

**Comment by rogrun** [comment]
#70

**Comment by thetrueavatar** [comment]
Didn't check..will trust you

**Comment by rogrun** [comment]
I think you had no intention of closing the PR and not merging it. Should I do a  new PR?

**Comment by thetrueavatar** [comment]
my bad thought I did the merge of the pr...

**Comment by thetrueavatar** [comment]
I have generated the phar. However it doesn't work everytime: I have got once in two
```
Message: Unable to get data for feature heating.power.consumption.total
 Reason: No such Feature
Code: 0
```
Do you have the same problem ? My guess would be a problem with viessman's api

**Comment by rogrun** [comment]
It work on my installation. 

When I call `print_r ($viessmannApi->getRawJsonData(""));`
 and search for `heating.power.consumption.total` and `heating.power.consumption` 
I found both entries at the json.

Maybe Viessmann does not support the feature at your heating

I think we should provide two functions like:

```
$viessmannApi->getHeatingPowerConsumption()
$viessmannApi->getHeatingPowerConsumptionTotal()
```

What do you think?

**Comment by thetrueavatar** [comment]
Seems to be a problem related with my php version. By setting the right version, I don't have the problem anymore.

**Comment by rogrun** [comment]
That makes me happy. In the next few days I will implement new fetures and expand the docs

**Pull request merged**
